CREATE TABLE IF NOT EXISTS system_users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  hashed_password VARCHAR(255),
  display_name VARCHAR(255),
  role VARCHAR(50) NOT NULL DEFAULT 'SYSTEM_ADMIN',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
